# Generated by Django 5.2.5 on 2025-08-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('LOGIN_FAIL', 'Login Failed'), ('LOGIN_SUCCESS', 'Login Success'), ('BRUTE_FORCE', 'Brute Force Attempt'), ('PORT_SCAN', 'Port Scan Detected'), ('MALWARE', 'Malware Alert')], max_length=50)),
                ('source_ip', models.GenericIPAddressField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
